import io
import zipfile
import pandas as pd
import json

class ExportUtils:
    @staticmethod
    def create_framework_zip(scripts_content: dict) -> bytes:
        """
        Creates an enterprise-grade Playwright framework structure in a ZIP file.
        scripts_content is a dict mapping filename to python code string.
        """
        zip_buffer = io.BytesIO()
        with zipfile.ZipFile(zip_buffer, "a", zipfile.ZIP_DEFLATED, False) as zip_file:
            # Create base directories
            for folder in ['tests/', 'pages/', 'utils/', 'testdata/', 'config/', 'reports/', 'screenshots/', 'logs/']:
                zip_file.writestr(folder, "")

            # Write standard files
            conftest_content = \"\"\"
import pytest
from playwright.sync_api import sync_playwright

@pytest.fixture(scope="session")
def browser():
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=False)
        yield browser
        browser.close()
\"\"\"
            zip_file.writestr("conftest.py", conftest_content.strip())
            
            pytest_ini_content = \"\"\"
[pytest]
addopts = --alluredir=reports
testpaths = tests
\"\"\"
            zip_file.writestr("pytest.ini", pytest_ini_content.strip())
            
            readme_content = \"\"\"
# Playwright Automation Framework
Generated by TestPilotAI.

## Structure
- `tests/`: Contains pytest test files.
- `pages/`: Page Object Model classes.
- `utils/`: Helper functions.
- `reports/`: Allure reports.
\"\"\"
            zip_file.writestr("README.md", readme_content.strip())

            # Write actual script contents provided by the user
            for filename, content in scripts_content.items():
                if content:
                    zip_file.writestr(f"tests/{filename}", content)

        return zip_buffer.getvalue()

    @staticmethod
    def export_test_cases_csv(markdown_table: str) -> bytes:
        # A simple hack to extract data from a markdown table using pandas
        # In a real scenario, this would use a robust markdown parser
        lines = markdown_table.strip().split('\\n')
        # Filter only table rows
        table_lines = [line for line in lines if '|' in line]
        if not table_lines:
            return b""
        
        # Convert to CSV format
        csv_content = []
        for line in table_lines:
            # Skip separator line like |---|---|
            if set(line.replace('|', '').replace('-', '').replace(' ', '')) == set():
                continue
            row = [cell.strip() for cell in line.split('|')[1:-1]]
            csv_content.append(','.join([f'"{c}"' for c in row]))
            
        return '\\n'.join(csv_content).encode('utf-8')
